apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
      app: {{ template "cassandra-k8s-operator.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  name: {{ template "cassandra-k8s-operator.name" . }}
